# Learning Numpy


In [9]:
import numpy as np
import sys

Python range vs Numpy arange

In [10]:
l = range(1000) #List of 1000 elements
print("list array:", len(l)*sys.getsizeof(l[0]) )

arr = np.arange(1000)
print("Numpy array: ", arr.size*arr.itemsize )

list array: 24000
Numpy array:  4000


Range is like an immutable iterable object
the numbers are not generated in the memory and is generated while iterating over

List is an more like an array and it is iterable

---
Whereas the numpy.array and numpy.arange produces the same thing
both produces numpy array but numpy.arange has a special ability where you can decide the step or space between numbers

In [11]:
print( type(np.array(2) ) )
print( type(np.arange(2) ) )

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


---
Array operations are so easy with np.array

In [12]:
a = np.array([1,2,3])
b = np.array([3,2,1])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

[4 4 4]
[-2  0  2]
[3 4 3]
[0.33333333 1.         3.        ]
[1 0 0]


---

Functions

In [14]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("np.size :", a.size)
print("np.shape :", a.shape)
print("np.ndim :", a.ndim)
print("np.itemsize :", a.itemsize)
print("np.dtype :", a.dtype)

np.size : 9
np.shape : (3, 3)
np.ndim : 2
np.itemsize : 4
np.dtype : int32


Changing data type and size

In [15]:
a = np.array([1])
print("np.array([1]) itemsize : ", a.itemsize)

a = np.array([1],dtype=np.int8)
print("np.array([1],dtype=np.int8) itemsize : ", a.itemsize)

np.array([1]) itemsize :  4
np.array([1],dtype=np.int8) itemsize :  1


In [19]:
a = np.zeros((2,4))
b = np.ones((2,4))  #Takes shape as an argument
print(a,'\n\n',b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Arrange Like rang

In [21]:
print(np.arange(1,10,2)) 

[1 3 5 7 9]


---

In [25]:
a = np.array([[1,3,4],[1,2,5]])
print("np.reshape() \n:" ,a.reshape(3,2))
print()
print("np.ravel() :" ,a.ravel()) 

np.reshape() 
: [[1 3]
 [4 1]
 [2 5]]

np.ravel() : [1 3 4 1 2 5]


min, max
sum , axis

In [27]:
print(a.sum())
print(a.max() , a.min())

16
5 1


---

axis = 0 means : Colum wise

axis = 0 means : Row wise


In [31]:
a = np.array([[1,2,3],[4,5,6]])
print("a :\n",a)
print()
print(a.sum(axis=0))
print()
print(a.sum(axis=1))

a :
 [[1 2 3]
 [4 5 6]]

[5 7 9]

[ 6 15]


Matrix product

In [35]:
b = np.array([[1,2],[2,4],[5,6]])
print("a : \n",a)
print("b : \n",b)
print()
print("a.b : \n" ,a.dot(b))

a : 
 [[1 2 3]
 [4 5 6]]
b : 
 [[1 2]
 [2 4]
 [5 6]]

a.b : 
 [[20 28]
 [44 64]]


### Indexing
both works

In [36]:
print(a)
print()
print(a[1,2])
print(a[1][2])

[[1 2 3]
 [4 5 6]]

6
6


### Stacking of arrays

In [43]:
a = np.arange(1,11).reshape(2,5)
print(f"a : \n {a}\n")

b = np.arange(1,20,2).reshape(2,5)
print(f"b : \n {b}\n")

c = np.vstack((a,b))
d = np.hstack((a,b))

print(f"np.vstack((a,b)) : \n {c} \n")
print(f"np.vstack((a,b)) : \n {d}")

a : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

b : 
 [[ 1  3  5  7  9]
 [11 13 15 17 19]]

np.vstack((a,b)) : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  3  5  7  9]
 [11 13 15 17 19]] 

np.vstack((a,b)) : 
 [[ 1  2  3  4  5  1  3  5  7  9]
 [ 6  7  8  9 10 11 13 15 17 19]]


#### hsplit : cut the rows 
#### vsplit : cut the colums 

In [69]:
a=np.arange(1,13).reshape(4,-1)
print(a)
print()
z = np.hsplit(a,3)
print("np.hsplit(a,4) : \n", z)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

np.hsplit(a,4) : 
 [array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


---
### Indexing with boolean array

In [70]:
print("a : \n",a)

b = a > 4
print("b : \n",b)

a : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b : 
 [[False False False]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]]


In [71]:
a[b] = -1
print('a : \n',a)

a : 
 [[ 1  2  3]
 [ 4 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
